export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED";

export const AUTH_REGISTRATION = "AUTH_REGISTRATION";
export const AUTH_REGISTRATION_SUCCESS = "AUTH_REGISTRATION_SUCCESS";
export const AUTH_REGISTRATION_FAILED = "AUTH_REGISTRATION_FAILED";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN ";

export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";
export const AUTH_CLEAR = "AUTH_CLEAR";
