export const DOCS_FETCH_DOCUMENTS = "DOCS_FETCH_DOCUMENTS";
export const DOCS_FETCH_DOCUMENTS_SUCCESS = "DOCS_FETCH_DOCUMENTS_SUCCESS";
export const DOCS_FETCH_DOCUMENTS_FAILED = "DOCS_FETCH_DOCUMENTS_FAILED";

export const DOCS_CREATE_DOCUMENT = "DOCS_CREATE_DOCUMENT";
export const DOCS_CREATE_DOCUMENT_SUCCESS = "DOCS_CREATE_DOCUMENT_SUCCESS";
export const DOCS_CREATE_DOCUMENT_FAILED = "DOCS_CREATE_DOCUMENT_FAILED";

export const DOCS_CLEAR_ERROR = "DOCS_CLEAR_ERROR";
export const DOCS_CLEAR = "DOCS_CLEAR";
