export const DOCS_FETCH_CREATED_DOCUMENTS = "DOCS_FETCH_DOCUMENTS";
export const DOCS_FETCH_CREATED_DOCUMENTS_SUCCESS = "DOCS_FETCH_DOCUMENTS_SUCCESS";
export const DOCS_FETCH_CREATED_DOCUMENTS_FAILED = "DOCS_FETCH_DOCUMENTS_FAILED";

export const DOCS_FETCH_SIGNING_DOCUMENTS = "DOCS_FETCH_SIGNING_DOCUMENTS";
export const DOCS_FETCH_SIGNING_DOCUMENTS_SUCCESS = "DOCS_FETCH_SIGNING_DOCUMENTS_SUCCESS";
export const DOCS_FETCH_SIGNING_DOCUMENTS_FAILED = "DOCS_FETCH_SIGNING_DOCUMENTS_FAILED";

export const DOCS_FETCH_DOCUMENT_FILE = "DOCS_FETCH_DOCUMENT_FILE";
export const DOCS_FETCH_DOCUMENT_FILE_SUCCESS = "DOCS_FETCH_DOCUMENT_FILE_SUCCESS";
export const DOCS_FETCH_DOCUMENT_FILE_FAILED = "DOCS_FETCH_DOCUMENT_FILE_FAILED";

export const DOCS_FETCH_DOC_SIGNATURES = "DOCS_FETCH_SIGNATURES";
export const DOCS_FETCH_DOC_SIGNATURES_SUCCESS = "DOCS_FETCH_SIGNATURES_SUCCESS";
export const DOCS_FETCH_DOC_SIGNATURES_FAILED = "DOCS_FETCH_SIGNATURES_FAILED";

export const DOCS_CREATE_DOCUMENT = "DOCS_CREATE_DOCUMENT";
export const DOCS_CREATE_DOCUMENT_SUCCESS = "DOCS_CREATE_DOCUMENT_SUCCESS";
export const DOCS_CREATE_DOCUMENT_FAILED = "DOCS_CREATE_DOCUMENT_FAILED";

export const DOCS_PROCESS_DOCUMENT = "DOCS_PROCESS_DOCUMENT";
export const DOCS_PROCESS_DOCUMENT_SUCCESS = "DOCS_PROCESS_DOCUMENT_SUCCESS";
export const DOCS_PROCESS_DOCUMENT_FAILED = "DOCS_PROCESS_DOCUMENT_FAILED";

export const DOCS_DELETE_DOCUMENT = "DOCS_DELETE_DOCUMENT";
export const DOCS_DELETE_DOCUMENT_SUCCESS = "DOCS_DELETE_DOCUMENT_SUCCESS";
export const DOCS_DELETE_DOCUMENT_FAILED = "DOCS_DELETE_DOCUMENT_FAILED";

export const DOCS_CLEAR_ERROR = "DOCS_CLEAR_ERROR";
export const DOCS_CLEAR = "DOCS_CLEAR";
