export const DOCS_FETCH_DOCUMENTS = "DOCS_FETCH_DOCUMENTS";
export const DOCS_FETCH_DOCUMENTS_SUCCESS = "DOCS_FETCH_DOCUMENTS_SUCCESS";
export const DOCS_FETCH_DOCUMENTS_FAILED = "DOCS_FETCH_DOCUMENTS_FAILED";
export const DOCS_CLEAR = "DOCS_CLEAR";
