export const ORGANIZATIONS_FETCH_ORGANIZATIONS = "ORGANIZATIONS_FETCH_ORGANIZATIONS";
export const ORGANIZATIONS_FETCH_ORGANIZATIONS_SUCCESS = "ORGANIZATIONS_FETCH_ORGANIZATIONS_SUCCESS";
export const ORGANIZATIONS_FETCH_ORGANIZATIONS_FAILED = "ORGANIZATIONS_FETCH_ORGANIZATIONS_FAILED";

export const ORGANIZATIONS_CREATE_ORGANIZATION = "ORGANIZATIONS_CREATE_ORGANIZATION";
export const ORGANIZATIONS_CREATE_ORGANIZATION_SUCCESS = "ORGANIZATIONS_CREATE_ORGANIZATION_SUCCESS";
export const ORGANIZATIONS_CREATE_ORGANIZATION_FAILED = "ORGANIZATIONS_CREATE_ORGANIZATION_FAILED";

export const ORGANIZATIONS_GET_CURRENT_ORGANIZATION = "ORGANIZATIONS_GET_CURRENT_ORGANIZATION";

export const ORGANIZATIONS_CLEAR = "ORGANIZATIONS_CLEAR";
