export const USERS_FETCH_USERS = "USERS_FETCH_USERS";
export const USERS_FETCH_USERS_SUCCESS = "USERS_FETCH_USERS_SUCCESS";
export const USERS_FETCH_USERS_FAILED = "USERS_FETCH_USERS_FAILED";

export const USERS_INVITE_USER = "USERS_INVITE_USER";
export const USERS_INVITE_USER_SUCCESS = "USERS_INVITE_USER_SUCCESS";
export const USERS_INVITE_USER_FAILED = "USERS_INVITE_USER_FAILED";

export const USERS_INVITE_SUCCESS_CLEAR = "USERS_INVITE_SUCCESS_CLEAR";
export const USERS_CLEAR = "USERS_CLEAR";
