export const USER_SET_USER = "USER_SET_USER";

export const USER_UPDATE = "USER_UPDATE";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED";

export const USER_FETCH_USER = "USER_FETCH_USER";
export const USER_FETCH_USER_SUCCESS = "USER_FETCH_USER_SUCCESS";
export const USER_FETCH_USER_FAILED = "USER_FETCH_USER_FAILED";

export const USER_CLEAR = "USER_CLEAR";
