export const WORKSPACES_FETCH_WORKSPACES = "WORKSPACES_FETCH_WORKSPACES";
export const WORKSPACES_FETCH_WORKSPACES_SUCCESS = "WORKSPACES_FETCH_WORKSPACES_SUCCESS";
export const WORKSPACES_FETCH_WORKSPACES_FAILED = "WORKSPACES_FETCH_WORKSPACES_FAILED";

export const WORKSPACES_FETCH_CURRENT_WORKSPACE = "WORKSPACES_FETCH_CURRENT_WORKSPACE";
export const WORKSPACES_FETCH_CURRENT_WORKSPACE_SUCCESS = "WORKSPACES_FETCH_CURRENT_WORKSPACE_SUCCESS";
export const WORKSPACES_FETCH_CURRENT_WORKSPACE_FAILED = "WORKSPACES_FETCH_CURRENT_WORKSPACE_FAILED";

export const WORKSPACES_CLEAR = "WORKSPACES_CLEAR";
