const light = {
  background: "#F8F9FB",
  color_text: "#263238",
  color_text_secondary: "#939499",
  color_error: "#d80404",
  primary_color: "#4F76E2",
  primary_text: "#3e6bdd",
  border_line: "1px solid #c7c7cc",
  input: { border_input: "1px solid #acb7c5", border_input_focus: "1px solid #2339c3" },
  page_auth: {
    color_error: "#d80404",
    color_link: "#2f49fb",
  },
  sidebar: {
    arrow: "#4D5F68",
    hover: { background: "#E4EBFA", color: "#678ABE" },
    header: { fontFamily: "Roboto-Medium", fontSize: "18px", margin: "20px 0 0" },
    default: { fontFamily: "Roboto", fontSize: "16px", margin: "5px 0" },
  },
  card: {
    background: "#fff",
    hover: "#e4ebfa",
    border: "1px solid #dadce0",
    color_subtitle: "#455a64",
    color_icon: "#455A64",
    color_preview: "#dae0f7",
  },
  preview: {
    tab: "#455A64",
    color_description: "#455a64",
    color_preview: "#dae0f7",
    dots: {
      color_grey: "#c7c7cc",
      color_primary: "#32e032",
      color_secondary: "#f4911d",
    },
  },
  button: {
    main: { background: "#477bff", color: "#fff" },
    outline: {
      background: "transparent",
      color: "#3e6bdd",
      color_border: "#4F76E2",
    },
    outlineRed: { background: "transparent", color: "#DF5753", color_border: "#DF5753" },
  },
  form: {
    info: "#a1a1a3",
    label: "#7f8587",
    text: "#263238",
    filter: "invert(0)",
  },
  modal: {
    backdrop: "blur(6px)",
    allScreen: {
      justifyContent: "flex-start",
      containerPadding: "0",
      rowPadding: " 20px 30px 0",
      height: "-webkit-fill-available",
      width: "-webkit-fill-available",
      maxWidth: "510px",
    },
    success: { rowPadding: "5px 0", containerPadding: "10px " },
  },
  scroll: { color: "#dee5f0", border: "1px solid #afb6c8", hover: "#9da9b9" },
  plugs: {
    constuction: {
      textSize: "22px",
      color: "#455A64",
      fontFamily: "Roboto-Bold",
      paddingText: "0 0 125px",
      paddingIcon: "0 0 20px",
    },
    success: {
      textSize: "22px",
      color: "#263238",
      fontFamily: "Roboto-Bold",
      // paddingText: "",
      paddingIcon: "20px",
      padding: "0 20px",
    },
    empty: { color: "#939499" },
  },
};
const dark = {
  background: "#24252d",
  color_text: "#e4e7f2",
  color_text_secondary: "#78839e",
  color_error: "#ff3a3a",
  primary_color: "#4F76E2",
  primary_text: "#5887ff",
  border_line: "1px solid #30313a",
  input: {
    border_input: "1px solid #4B5057",
    border_input_focus: "1px solid #4a5bc4",
  },
  page_auth: {
    color_error: "#ff3a3a",
    color_link: "#5481ff",
  },
  sidebar: {
    arrow: "#78839e",
    hover: { background: "#313543", color: "#95a0b9" },
    header: { fontFamily: "Roboto-Medium", fontSize: "18px", margin: "20px 0 0" },
    default: { fontFamily: "Roboto", fontSize: "16px", margin: "5px 0" },
  },
  card: {
    background: "#2a2d3a",
    hover: "#477bff",
    border: "0",
    color_subtitle: "#8e97ab",
    color_icon: "#8e97ab",
    color_preview: "#313543",
  },
  preview: {
    tab: "#78839e",
    color_description: "#c7d3df",
    color_preview: "#313543",
    dots: {
      color_grey: "#66666c",
      color_primary: "#42a042",
      color_secondary: "#ba6d13",
    },
  },
  button: {
    main: { background: "#477bff", color: "#fff" },
    outline: {
      background: "transparent",
      color: "#4F76E2",
      color_border: "#477bff",
    },
    outlineRed: { background: "transparent", color: "#e6615d", color_border: "#DF5753" },
  },
  form: {
    info: "#8a939d",
    label: "#a2acb8",
    text: "#d3dde7",
    filter: "invert(1)",
  },
  modal: {
    backdrop: "blur(6px) brightness(0.3)",
    allScreen: {
      justifyContent: "flex-start",
      containerPadding: "0",
      rowPadding: " 20px 30px 0",
      height: "-webkit-fill-available",
      width: "-webkit-fill-available",
      maxWidth: "510px",
    },
    success: { rowPadding: "5px 0", containerPadding: "10px " },
  },
  scroll: { color: "#4d535c", border: "1px solid #4b5057", hover: "#636a75" },
  plugs: {
    constuction: {
      textSize: "22px",
      color: "#adb3b6",
      fontFamily: "Roboto-Bold",
      paddingText: "0 0 125px",
      paddingIcon: "0 0 20px",
    },
    success: {
      textSize: "22px",
      fontFamily: "Roboto",
      // paddingText: "",
      paddingIcon: "20px",
      padding: "0 20px",
    },
    empty: { color: "#8a939d" },
  },
};
export const themes = { light, dark };
